config/routes.rb
Rails.application.routes.draw do
  resources :screenwriters
  resources :search
  resources :directors
  resources :actors
  resources :sessions
  resources :users
  resources :genres
  root 'movies#index'
  resources :movies do
  	resources :comments
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
  validates :name, presence: true, length: {minimum: 2}
  validates :birthday, presence: true
  validates :description, presence: true, length: {minimum: 1}
  validates :country, presence: true
  
  has_attached_file :photo, style: {large: "450x450", thumb: "50x50#"}
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

    belongs_to :user
    has_many :actors_movies
    has_many :movies, through: :actors_movies

  def self.search(params)
		actors = Actor.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
		actors	
	end
end

app/models/actors_movie.rb
class ActorsMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :commenter, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 5 }
  validates :rating, presence: true

  belongs_to :movie
  belongs_to :user

end

app/models/director.rb
class Director < ApplicationRecord
  has_many :directors_movies
  has_many :movies, through: :directors_movies

  def self.search(params)
		directors = Director.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
		directors	
  end
end

app/models/directors_movie.rb
class DirectorsMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :director
end

app/models/genre.rb
class Genre < ApplicationRecord
	
  has_many :genres_movies
  has_many :movies, through: :genres_movies

end

app/models/genres_movie.rb
class GenresMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/movie.rb
class Movie < ApplicationRecord

  validates :name, presence: true, length: {minimum: 2}
  validates :premiere_date, presence: true
  validates :length, presence: true, length: {minimum: 1}
  validates :description, presence: true, length: {minimum: 1}
  validates :country, presence: true
  
    has_many :comments, dependent: :destroy
    belongs_to :user
    has_many :genres_movies
    has_many :genres, through: :genres_movies
    has_many :directors_movies
    has_many :directors, through: :directors_movies
    has_many :actors_movies
    has_many :actors, through: :actors_movies

    has_many :movies_screenwriters
    has_many :screenwriters, through: :movies_screenwriters

    has_attached_file :movie, style:
      {
        medium: {geometry: "100x50", format: 'mp4'},
        thumb: {geometry: "50x50", format: 'jpg', time: 10} 
      }, processor: [:transcoder]
    validates_attachment_content_type :movie, content_type: /\Avideo\/.*\z/

  def self.search(params)
		movies = Movie.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
		movies	
	end
  
end

app/models/movies_screenwriter.rb
class MoviesScreenwriter < ApplicationRecord
  belongs_to :movie
  belongs_to :screenwriter
end

app/models/screenwriter.rb
class Screenwriter < ApplicationRecord
  has_many :movies_screenwriters
  has_many :movies, through: :movies_screenwriters

  def self.search(params)
		screenwriters = Screenwriter.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
		screenwriters	
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true, 
    :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

    has_many :movies, foreign_key: :user_id
    has_many :actors, foreign_key: :user_id
    has_many :comments, foreign_key: :user_id
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :find_movie, only: [:show, :edit, :update, :destroy]
    before_action :admin_authorize, except: [:index, :show]

  def index
    @movies = Movie.all.order(:name)
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
      if @movie.save
        redirect_to movie_path(@movie)
      else
        render 'new'
      end
  end

  def show
    # @movie = Movie.find(params[:id])
    # find_movie
  end

  def edit
    # @movie = Movie.find(params[:id])
    # find_movie
  end

  def update
   # @movie = Movie.find(params[:id])
   # find_movie
      if @movie.update(movie_params)
        redirect_to movie_path(@movie)
      else
        render 'edit'
      end
  end

  def destroy
   # @movie = Movie.find(params[:id])
   # find_movie
    @movie.destroy
    redirect_to movies_path
  end

private

  def movie_params
    params.require(:movie).permit(:name, :premiere_date,:length, :description, :scenarist, :country, :user_id, :movie, genre_ids: [], director_ids: [], actor_ids: [], screenwriter_ids: [])
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/movies/_form.html.erb
<%= render 'common/errors', model: @movie %>

  <%= form_for @movie, html: {multipart: true} do |f| %>

    <div class="field" style="100%;">
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control' %>
      </p>
      <p>
        <%= f.label :premiere_date %><br>
        <%= f.date_field :premiere_date, class: 'form-control' %>
      </p>
      <p>
        <%= f.label :length %><br>
        <%= f.number_field :length, class: 'form-control' %>
      </p>
      <p>
        <%= f.label :description %><br>
        <%= f.text_area :description, class: 'form-control' %>
      </p>
      <p>
        <%= f.label :genre %><br>
        <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name %>
      <p>
        <%= f.label :director %><br>
        <%= f.collection_check_boxes :director_ids, Director.all, :id, :name %>  
      </p>
      <p>
        <%= f.label :screenwriter %><br>
        <%= f.collection_check_boxes :screenwriter_ids, Screenwriter.all, :id, :name %>  
      </p>
      <p>
        <%= f.label :actor %><br>
        <%= f.collection_check_boxes :actor_ids, Actor.all, :id, :name %>  
      </p>
      <p>
        <%= f.label :country %><br>
        <%= f.select :country, options_for_select(['Polska', 'Argentyna', 'Czechy', 'USA', 'Wielka Brytania', 'Francja', 'Niemcy']) %>
      </p>
        <%= f.hidden_field :user_id, value: session[:user_id] %>
      <p>
      <p>
        <%= f.label :trailer %><br>
        <%= f.file_field :movie, class: 'form-control' %>
      </p>
      <p>
        <%= f.submit class: 'btn btn-lg btn-success'%>
      </p>
    </div>
  <% end %>

app/views/movies/edit.html.erb
<div class="row" style="padding-top: 30px;">
  <div class="col"> </div>
    <div class="col-md-7">

      <h3>Edit film</h3>

        <%= render "form" %>

          <%= link_to "Back", movies_path, class: 'btn btn-md btn-info' %>

    </div>
  <div class="col"> </div>
</div>

app/views/movies/index.html.erb
<div class="row" style="padding-top: 10px;">
  <div class="col"> </div>
    <div class="col-md-12">

      <h2>List of movies: </h2>

        <% if current_user && current_user.admin? %>

    <p>
        <%= link_to "Add new movie", new_movie_path, class: 'btn btn-lg btn-info' %>
    </p>

        <% end %>

    <table class="table table-hover">
      <thead>
        <tr class="table-primary">
        <% if current_user && current_user.admin? %>

          <th>Title</th>
          <th>Premiere</th>
          <th>Length</th>
          <th>Description</th>
          <th>Genre</th>
          <th>Director</th>
          <th>Scenarist</th>
          <th>Actor</th>
          <th>Country</th>
          <th colspan="3">Editing Options</th>

        <% else %>

          <th>Title</th>
          <th>Premiere</th>
          <th>Length</th>
          <th>Description</th>
          <th>Genre</th>
          <th>Director</th>
          <th>Scenarist</th>
          <th>Actor</th>
          <th>Country</th>
          <th colspan="1">Options</th>

        <% end %>

        </tr>
      </thead>
      <tbody>
          <% @movies.each do |movie| %>
        <tr class="table-success">
          <td><%= movie.name %></td>
          <td><%= movie.premiere_date.strftime("%d.%m.%Y")%></td>
          <td><%= movie.length %></td>
          <td><%= truncate(movie.description, length: 25) %></td>
          <td>
            <% movie.genres.each do |g| %>
              <%= g.name %>
            <% end %>
          </td>
          <td>
            <% movie.directors.each do |g| %>
              <%= g.name %>
            <% end %>
          </td>
          <td>
            <% movie.screenwriters.each do |g| %>
              <%= g.name %>
            <% end %>
          </td>
           <td>
            <% movie.actors.each do |g| %>
              <%= g.name %>
            <% end %>
          </td>
          <td><%= movie.country %></td> 

          <td><%= link_to 'Show', movie_path(movie), class: 'btn btn-sm btn-info'%></td>

          <% if current_user && current_user.admin? %>

          <td><%= link_to 'Edit', edit_movie_path(movie), class: 'btn btn-sm btn-warning' %></td>
          <td><%= link_to 'Delete', movie_path(movie), class: 'btn btn-sm btn-danger', method: :delete, data: {confirm: "Are you sure?"} %></td>

          <% end %>
          
        </tr>
          <% end %>
      </tbody>
    </table>

    </div>
  <div class="col"> </div>
</div>

app/views/movies/new.html.erb
<div class="row" style="padding-top: 30px;">
  <div class="col"> </div>
    <div class="col-md-7">

      <h3>Add new film</h3>

        <%= render 'form' %>

        <%= link_to "Back", movies_path, class: 'btn btn-md btn-info' %>

    </div>
  <div class="col"> </div>
</div>

app/views/movies/search.html.erb
<div class="row">
	<div class="col"></div>
	  <div class="col-md-6">
	  	
		<h4>List of all searched Movies</h4>
	
		<table class="table table-hover table-striped table-responsive-xs table-danger">
			<tr>
			  <th>Title</th>
			  <th>Text</th>
			  <th colspan="1">Show Movies</th>
			</tr>
				<% @movies.each do |movie| %>
			<tr>
			  <td>
				<%= movie.name %>
			  </td>
			  <td>
				<%= truncate(movie.description, length: 75) %>
			  </td>	
			  <td>
				<%= link_to 'Show', movie_path(movie), class: 'btn btn-sm btn-info' %>
			  </td>
			    <% end %>
			</tr>
		</table>
			<p>
				<%= link_to 'Back', movies_path, class: 'btn btn-sm btn-primary'  %>
			</p>
	  </div>
	<div class="col"></div>
</div>

app/views/movies/show.html.erb
<div class="row" style="padding-top: 30px;">
  <div class="col"> </div>
    <div class="col-md-10">
        <p>
          <strong>Title:</strong>
            <%= @movie.name %>
        </p>
        <p>
          <strong>Date:</strong>
            <%= @movie.premiere_date.strftime("%d.%m.%Y") %>
        </p>
        <p>
          <strong>Length:</strong>
            <%= @movie.length %> minutes
        </p>
        <p>
          <strong>Description</strong>
            <%= @movie.description %>
        </p>
        <p>
          <strong>Genres</strong>
            <% @movie.genres.each do |genre| %>
            <%= link_to genre.name, genre_path(genre) %>
            <% end %> 
        </p>
        <p>
          <strong>Directors</strong>
            <% @movie.directors.each do |director| %>
            <%= link_to director.name, director_path(director) %>
            <% end %> 
        </p>
        <p>
          <strong>Screenwriters</strong>
            <% @movie.screenwriters.each do |screenwriter| %>
            <%= link_to screenwriter.name, screenwriter_path(screenwriter) %>
            <% end %> 
        </p>
          <p>
          <strong>Actors</strong>
            <% @movie.actors.each do |actor| %>
            <%= link_to actor.name, actor_path(actor) %>
            <% end %> 
        </p>
        <p>
          <strong>Country:</strong>
            <%= @movie.country %>
        </p>
        <p>
          <% if @movie.movie.present? %>
            <%= video_tag(@movie.movie, controls: true, type: 'video/mp4', style: "width:25%") %>
          <% end %>
        </p>

        <p>
          <strong>Created at:</strong>
            <%= @movie.created_at %>
        </p>
        <p>
          <strong>Updated at:</strong>
            <%= @movie.updated_at %>
        </p>

      <div class="field" style="100%;">
      
        <h4>Add comment</h4>

          <% if current_user %>
        
          <%= render 'comments/form' %>

          <% else %>

            <%= link_to 'Sign In', new_session_path %> or 
            <%= link_to 'Sign Up', new_user_path %> to created a comment.

          <% end %>

        <h4>Comments</h4>
      
          <%= render @movie.comments.order(created_at: :desc) %><br>

          <%= link_to 'Back', movies_path, class: 'btn btn-md btn-info' %>
        
      </div>
    </div>
  <div class="col"> </div>
</div>