config/routes.rb
Rails.application.routes.draw do
  resources :screenwriters
  resources :search
  resources :directors
  resources :actors
  resources :sessions
  resources :users
  resources :genres
  root 'movies#index'
  resources :movies do
  	resources :comments
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
  validates :name, presence: true, length: {minimum: 2}
  validates :birthday, presence: true
  validates :description, presence: true, length: {minimum: 1}
  validates :country, presence: true
  
  has_attached_file :photo, style: {large: "450x450", thumb: "50x50#"}
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

    belongs_to :user
    has_many :actors_movies
    has_many :movies, through: :actors_movies

  def self.search(params)
		actors = Actor.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
		actors	
	end
end

app/models/actors_movie.rb
class ActorsMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :commenter, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 5 }
  validates :rating, presence: true

  belongs_to :movie
  belongs_to :user

end

app/models/director.rb
class Director < ApplicationRecord
  has_many :directors_movies
  has_many :movies, through: :directors_movies

  def self.search(params)
		directors = Director.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
		directors	
  end
end

app/models/directors_movie.rb
class DirectorsMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :director
end

app/models/genre.rb
class Genre < ApplicationRecord
	
  has_many :genres_movies
  has_many :movies, through: :genres_movies

end

app/models/genres_movie.rb
class GenresMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/movie.rb
class Movie < ApplicationRecord

  validates :name, presence: true, length: {minimum: 2}
  validates :premiere_date, presence: true
  validates :length, presence: true, length: {minimum: 1}
  validates :description, presence: true, length: {minimum: 1}
  validates :country, presence: true
  
    has_many :comments, dependent: :destroy
    belongs_to :user
    has_many :genres_movies
    has_many :genres, through: :genres_movies
    has_many :directors_movies
    has_many :directors, through: :directors_movies
    has_many :actors_movies
    has_many :actors, through: :actors_movies

    has_many :movies_screenwriters
    has_many :screenwriters, through: :movies_screenwriters

    has_attached_file :movie, style:
      {
        medium: {geometry: "100x50", format: 'mp4'},
        thumb: {geometry: "50x50", format: 'jpg', time: 10} 
      }, processor: [:transcoder]
    validates_attachment_content_type :movie, content_type: /\Avideo\/.*\z/

  def self.search(params)
		movies = Movie.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
		movies	
	end
  
end

app/models/movies_screenwriter.rb
class MoviesScreenwriter < ApplicationRecord
  belongs_to :movie
  belongs_to :screenwriter
end

app/models/screenwriter.rb
class Screenwriter < ApplicationRecord
  has_many :movies_screenwriters
  has_many :movies, through: :movies_screenwriters

  def self.search(params)
		screenwriters = Screenwriter.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
		screenwriters	
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true, 
    :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

    has_many :movies, foreign_key: :user_id
    has_many :actors, foreign_key: :user_id
    has_many :comments, foreign_key: :user_id
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]
  before_action :admin_authorize, except: [:index, :show, :search]

  def index
    @directors = Director.all
  end

  def new
    @director = Director.new
  end

  def create
    @director = Director.new(director_params)
      if @director.save
        redirect_to director_path(@director)
      else
        render 'new'
      end
  end

  def edit
  end

  def update
    if @director.update(director_params)
        redirect_to director_path(@director)
      else
        render 'edit'
      end
  end

  def show
  end

  def destroy
    @director.destroy
    redirect_to directors_path
  end

private
    
  def set_director
    @director = Director.find(params[:id])
  end

  def director_params
    params.require(:director).permit(:name, :description)
  end
  
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/screenwriter_helper.rb
module ScreenwriterHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/directors/_form.html.erb
<%= render 'common/errors', model: @director %>

<%= form_with(model: director, local: true) do |f| %>

  <div class="field" style="100%;">
  	<p>
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </p>
    <p>
        <%= f.label :description %><br>
        <%= f.text_area :description, class: 'form-control' %>
    </p>
    <p>
      <%= f.submit class: 'btn btn-lg btn-success' %>
    </p>

  </div>
<% end %>

app/views/directors/edit.html.erb
<div class="row" style="padding-top: 30px;">
  <div class="col"> </div>
    <div class="col-md-7">

      <h1>Editing Director</h1>

        <%= render 'form', director: @director %>

        <%= link_to 'Back', directors_path, class: 'btn btn-md btn-info' %>

    </div>
  <div class="col"> </div>
</div>

app/views/directors/index.html.erb
<div class="row" style="padding-top: 10px;">
  <div class="col"> </div>
    <div class="col-md-12">

      <h4>Directors</h4>

        <% if current_user && current_user.admin? %>

          <p>
            <%= link_to 'New Director', new_director_path, class: 'btn btn-lg btn-info' %>
          </p>
        <% end %>

        <table class="table table-hover">
          <thead>
            <tr class="table-light">
              <% if current_user && current_user.admin? %>
                <th>Name</th>
                <th>Description</th>
                <th colspan="3">Editing Options</th>

              <% else %>

                  <th>Name</th>
                  <th>Description</th>
                  <th colspan="1">Options</th>

              <% end %>
            </tr>
          </thead>

          <tbody>

            <% @directors.each do |director| %>

              <tr class="table-dark text-dark">
                  <td><%= director.name %></td>
                  <td><%= director.description %></td>
                  <td><%= link_to 'Show', director, class: 'btn btn-md btn-info' %></td>

                <% if current_user && current_user.admin? %>

                  <td><%= link_to 'Edit', edit_director_path(director), class: 'btn btn-md btn-warning' %></td>
                  <td><%= link_to 'Destroy', director, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-md btn-danger' %></td>

                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>

    </div>
  <div class="col"> </div>
</div>

app/views/directors/new.html.erb
<div class="row" style="padding-top: 30px;">
  <div class="col"> </div>
    <div class="col-md-7">
    	
      <h1>New Director</h1>

        <%= render 'form', director: @director %>

        <%= link_to 'Back', directors_path, class: 'btn btn-md btn-info' %>

    </div>
  <div class="col"> </div>
</div>

app/views/directors/show.html.erb
<div class="row" style="padding-top: 30px;">
  <div class="col"> </div>
    <div class="col-md-10">

      <p>
        <strong>Name:</strong>
        <%= @director.name %>
      </p>
      <p>
        <strong>Description:</strong>
          <%= @director.description %>
      </p>
 
      <%= link_to 'Back', directors_path, class: 'btn btn-md btn-info' %>

    <% if current_user && current_user.admin? %>

      <%= link_to 'Edit', edit_director_path(@director), class: 'btn btn-md btn-warning' %>
      <%= link_to 'Destroy', @director, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-md btn-danger' %>

    <% end %>
 
  </div>
  <div class="col"> </div>
</div>