config/routes.rb
Rails.application.routes.draw do
  resources :screenwriters
  resources :search
  resources :directors
  resources :actors
  resources :sessions
  resources :users
  resources :genres
  root 'movies#index'
  resources :movies do
  	resources :comments
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
  validates :name, presence: true, length: {minimum: 2}
  validates :birthday, presence: true
  validates :description, presence: true, length: {minimum: 1}
  validates :country, presence: true
  
  has_attached_file :photo, style: {large: "450x450", thumb: "50x50#"}
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

    belongs_to :user
    has_many :actors_movies
    has_many :movies, through: :actors_movies

  def self.search(params)
		actors = Actor.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
		actors	
	end
end

app/models/actors_movie.rb
class ActorsMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :commenter, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 5 }
  validates :rating, presence: true

  belongs_to :movie
  belongs_to :user

end

app/models/director.rb
class Director < ApplicationRecord
  has_many :directors_movies
  has_many :movies, through: :directors_movies

  def self.search(params)
		directors = Director.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
		directors	
  end
end

app/models/directors_movie.rb
class DirectorsMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :director
end

app/models/genre.rb
class Genre < ApplicationRecord
	
  has_many :genres_movies
  has_many :movies, through: :genres_movies

end

app/models/genres_movie.rb
class GenresMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/movie.rb
class Movie < ApplicationRecord

  validates :name, presence: true, length: {minimum: 2}
  validates :premiere_date, presence: true
  validates :length, presence: true, length: {minimum: 1}
  validates :description, presence: true, length: {minimum: 1}
  validates :country, presence: true
  
    has_many :comments, dependent: :destroy
    belongs_to :user
    has_many :genres_movies
    has_many :genres, through: :genres_movies
    has_many :directors_movies
    has_many :directors, through: :directors_movies
    has_many :actors_movies
    has_many :actors, through: :actors_movies

    has_many :movies_screenwriters
    has_many :screenwriters, through: :movies_screenwriters

    has_attached_file :movie, style:
      {
        medium: {geometry: "100x50", format: 'mp4'},
        thumb: {geometry: "50x50", format: 'jpg', time: 10} 
      }, processor: [:transcoder]
    validates_attachment_content_type :movie, content_type: /\Avideo\/.*\z/

  def self.search(params)
		movies = Movie.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
		movies	
	end
  
end

app/models/screenwriter.rb
class Screenwriter < ApplicationRecord
  has_many :movies_screenwriters
  has_many :movies, through: :movies_screenwriters

  def self.search(params)
		screenwriters = Screenwriter.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
		screenwriters	
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true, 
    :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

    has_many :movies, foreign_key: :user_id
    has_many :actors, foreign_key: :user_id
    has_many :comments, foreign_key: :user_id
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_errors.html.erb
<% if model.errors.any? %>
  <div>
    <h4>
    	<%= pluralize(model.errors.count, 'error') %> prohibited this position from being save: 
    </h4>
    <hr/>
    <ul>
        <% model.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<section class="footer">
	<div class="row">
		<div class="col-md-4">
			<h5 class="text-center"><%= link_to 'Facebook', 'https://pl-pl.facebook.com', :target => "_blank" %></h5>	
		</div>
		<div class="col-md-4">
			<h5 class="text-center"><%= link_to 'Twitter', 'https://twitter.com/?lang=pl', :target => "_blank"  %></h5>	
		</div>
		<div class="col-md-4">
			<h5 class="text-center"><%= link_to 'Youtube', 'https://www.youtube.com/?gl=PL&hl=pl', :target => "_blank"  %></h5>	
		</div>
	</div><hr>
	<p class="small-font dark">© 2018 Moviesweb</p>
</section>

app/views/shared/_navigation.html.erb
 <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Movies', movies_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Actors', actors_path %>
        </li>

        <li class="nav-item">
          <%= link_to 'Directors', directors_path %>
        </li>

        <li class="nav-item">
          <%= link_to 'Screenwriters', screenwriters_path %>
        </li>

          <% if current_user && current_user.admin? %>

        <li class="nav-item">
          <%= link_to 'Genres', genres_path %>
        </li>

          <li class="nav-item">
            <%= link_to 'Sign Out', session_path('active'), method: :delete %>
          </li>

            <% elsif current_user %>

          <li class="nav-item">
            <%= link_to 'Sign Out', session_path('active'), method: :delete %>
          </li>
            
            <% else %>

          <li class="nav-item">
            <%= link_to 'Sign In', new_session_path %>
          </li>

          <li class="nav-item">
              <%= link_to 'Create Account', new_user_path %>
          </li>
          
            <% end %>
      </ul>

        <div class="form-inline mt-2 mt-md-0">
          <%= form_tag search_index_path, method: :get do %>
          <%= text_field_tag :search, nil, placeholder: "Search", class: "form-control mr-sm-2" %>
          <%= submit_tag "Search", class: "btn btn-light my-2 my-sm-0" %>

          <% end %>

        </div>
    </div>
</nav>